### ISSUE TITLE
trabalho-01: análise comparativa

### ISSUE THREAD

**Issue by fsantanna** [isabarbalho/EDL#2]
Isabelle,

A avaliação comparativa precisa ser estendida.
Em particular, em termos de expressividade, o que Fortran oferece que outras linguagens não oferecem?
Também sugiro mostrar exemplos de código que "vendam" a linguagem, i.e., exemplos que mostrem algo interessante da linguagem.

**Comment by fsantanna** [comment]
(já considero que foi entregue dentro do prazo)

**Comment by isabarbalho** [comment]
ok. Farei as devidas alterações.

**Comment by isabarbalho** [comment]
Boa noite professor,
Fiz algumas alterações nos tópicos Classificação / Avaliação Comparativa do ARTIGO.md e mudei o modelo de comparação do slides.pdf 
Até amanhã mudarei a parte de código representativo.

**Comment by isabarbalho** [comment]
Boa tarde professor,
na quarta mesmo eu fiz os últimos ajustes e mandei!

**Comment by fsantanna** [comment]
Ficou faltando o exemplo de código representativo, não?

**Comment by isabarbalho** [comment]
coloquei no slide

**Comment by fsantanna** [comment]
ok. Seria bom copiar os exemplos para o artigo também. Os slides com a apresentação são uma outra avaliação.

**Comment by isabarbalho** [comment]
ah, tudo bem! farei essas alterações

**Comment by isabarbalho** [comment]
Pronto. Fiz as alterações. Desculpa a confusão.

**Comment by fsantanna** [comment]
ok
